### ISSUE TITLE
Negative decimal numbers not parsed correctly

### ISSUE THREAD

**Issue by tomvansteijn** [mapbox/snuggs#16]
Came here via rasterio calc. Apparently snuggs does not parse negative decimal numbers correctly. 

Below statement returns False:
```
snuggs.eval("(< -0.9 0)")
```
Comparing with a whole negative number returns True:
```
snuggs.eval("(< -1 0)")
```
Apparently the parser misses the sign when parsing a decimal number above -1. Compare:
```
snuggs.eval("(+ -0.9 0)")
snuggs.eval("(+ -1.7 0)")
```

**Comment by sgillies** [comment]
@tomvansteijn thanks for the report! I'm now using hypothesis to hammer on the number parsers and found another bug, also fixed. 1.4.4 is on PyPI now and has both the fixes.
