### ISSUE TITLE
Support for None/null/nil

### ISSUE THREAD

**Issue by sgillies** [mapbox/snuggs#2]
Specifically so we can evaluate

```
"(asarray (fillnodata (band 1 1) nil 20) (fillnodata (band 1 2) nil 20) (fillnodata (band 1 3) nil 20))"
```

with rio-calc, specifying a smaller max search distance.

**Comment by sgillies** [comment]
@dnomadb the default value for fillnodata's max search distance is 100. Running it with a value of 20 (as in the expression above) works and produces this output:

![out](https://cloud.githubusercontent.com/assets/33697/6912109/4f0b65b4-d728-11e4-8952-5a472e5aa467.jpg)

Compare to the default (100) result:

![](https://cloud.githubusercontent.com/assets/33697/6204500/b4ea50ec-b50a-11e4-8b95-c3ee299f707c.jpg)

**Comment by dnomadb** [comment]
^^ awesome, this is great @sgillies
