### ISSUE TITLE
how to test nan

### ISSUE THREAD

**Issue by fabricebrito** [mapbox/snuggs#25]
I have nan in an array and for instance `data[7772, 4465] `is `nan`

If I do:
`snuggs.eval("(== d a)", d=data[7772, 4465], a=data[7772, 4465])`
I get 
`False`

How do I to the test nan in data?

**Comment by sgillies** [comment]
`nan == nan` always evaluates to False in Python. That's the way it is. You will need to replace or mask out the nans in your data.
