### ISSUE TITLE
Transfer to rasterio org alongside rasterio

### ISSUE THREAD

**Issue by sgillies** [mapbox/snuggs#26]
@jqtrde @pratikyadav whadaya think about transferring this repo to https://github.com/rasterio? We can vendor it if we have to, but if you want it off your hands, we're happy to have it in the rasterio org.

**Comment by pratikyadav** [comment]
👍  From me.

**Comment by jqtrde** [comment]
@sgillies! I'll try and get this moving.

**Comment by sgillies** [comment]
@jqtrde I'm moving on and am forking and vendoring snuggs in projects where needed.
